spring:
  application:
    name: blogyg-server-client
  zipkin:
    base-url: http://blogyg:8777

server:
  port: 8444

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/

---
#spring:
#  application:
#    name: blogyg-server-client
#  zipkin:
#    base-url: http://blogyg:8777
#
#server:
#  port: 8333
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://blogyg:8111/eureka/

