#spring:
#  application:
#    name: blogyg-server-client
#
#server:
#  port: 8444
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8111/eureka/

---
spring:
  application:
    name: blogyg-server-client

server:
  port: 8333

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8111/eureka/

