spring:
  application:
    name: blogyg-server-ribbon
  profiles:
    active: prod
  zipkin:
    base-url: http://blogyg:8777

server:
  port: 8222

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/

management:
  endpoint:
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'

# spring-boot-admin监控日志，需要填写绝对路径，暂时不清楚怎么能通过相对路径获取日志文件
logging:
  file: C:\Users\young\IdeaProjects\spring-cloud-blogyg\logs\blogyg-server-ribbon\debug.log
