spring:
  application:
    name: blogyg-server-ribbon
  zipkin:
    base-url: http://blogyg:8777

server:
  port: 8222

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/
