spring:
  application:
    name: blogyg-server-ribbon
  zipkin:
    base-url: http://blogyg:8777
  boot:
    admin:
      client:
        url: http://blogyg:9002
server:
  port: 8222

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/
