version: '2'
services:
  blogyg-server-eureka:
    image: harbor.blogyg.cn/blogyg/blogyg-server-eureka:v1.0.0
    restart: always
    ports:
      - "8111:8111"
#    environment:
#      - spring.profiles.active=dev
    volumes:
      - /data/docker/logs/blogyg-server-eureka/:/opt/app/logs/blogyg-server-eureka/
    extra_hosts:
      - "blogyg:172.16.22.164"
    networks:
      - blogyg

  blogyg-server-client:
    image: harbor.blogyg.cn/blogyg/blogyg-server-client:v1.0.0
    restart: always
    ports:
      - "8444:8444"
    #    environment:
    #      - spring.profiles.active=dev
    volumes:
      - /data/docker/logs/blogyg-server-client/:/opt/app/logs/blogyg-server-client/
    extra_hosts:
      - "blogyg:172.16.22.164"
    networks:
      - blogyg

networks:
  blogyg:
    driver: bridge
