version: '2'
services:
  blogyg-server-monitor:
    image: harbor.blogyg.cn/blogyg/blogyg-server-monitor:v1.0.0
    restart: always
    ports:
      - "9002:9002"
#    environment:
#      - spring.profiles.active=dev
    volumes:
      - /data/docker/logs/blogyg-server-monitor/:/opt/app/logs/blogyg-server-monitor/
    extra_hosts:
      - "blogyg:172.16.22.164"
    networks:
      - blogyg

networks:
  blogyg:
    driver: bridge
