spring:
  application:
    name: blogyg-server-zuul
  zipkin:
    base-url: http://blogyg:8777
  boot:
    admin:
      client:
        url: http://blogyg:9002
server:
  port: 8666

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/

zuul:
  routes:
    api-r:
      path: /api/r/**
      serviceId: blogyg-server-ribbon
    api-f:
      path: /api/f/**
      serviceId: blogyg-server-feign
    api-c:
      path: /api/c/**
      serviceId: blogyg-server-client
