spring:
  application:
    name: blogyg-server-zipkin
  boot:
    admin:
      client:
        url: http://blogyg:9002
server:
  port: 8777

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
