spring:
  application:
    name: blogyg-server-zipkin

server:
  port: 8777

eureka:
  client:
    serviceUrl:
      defaultZone: http://blogyg:8111/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
